try to provide better error message if there is an exception in the nailgun launcher or appilcation script

diff --git a/cbt b/cbt
--- a/cbt
+++ b/cbt
@@ -181,7 +181,9 @@ stage1 () {
 			log "Checking if nailgun is up yet." $*
 			$NG cbt.NailgunLauncher cbt.CheckAlive $CP "$CWD" $* >> $NAILGUN/target/nailgun.stdout.log 2>> $NAILGUN/target/nailgun.stderr.log
 			alive=$?
-			if [[ $alive -eq 33 ]]; then
+			if [[ $alive -eq 131 ]]; then
+				echo "Nailgun call failed. Try 'cbt kill' and check the error log cbt/nailgun_launcher/target/nailgun.stderr.log" 1>&2
+			elif [[ $alive -eq 33 ]]; then
 				break
 			else
 				log "Nope. Sleeping for 1 second" $*
